version: '3'
services:
  postgres:
    image: registry.redhat.io/rhel8/postgresql-13:1-31.1645816955
    container_name: postgres
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      POSTGRESQL_USER: postgres
      POSTGRESQL_PASSWORD: postgres
      POSTGRESQL_DATABASE: postgres
  pgweb:
    image: docker.io/sosedoff/pgweb
    container_name: pgweb
    restart: on-failure
    links:
      - postgres
    ports:
      - 8081:8081
    environment:
      # sslmode=disable because: https://github.com/sosedoff/pgweb/issues/23#issuecomment-60840307
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
